package com.epc.platform.service.mapper.dictionary;

import com.epc.platform.service.domain.dictionary.SysDictionary;
import com.epc.platform.service.domain.dictionary.SysDictionaryCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.session.RowBounds;

public interface SysDictionaryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int countByExample(SysDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int deleteByExample(SysDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int deleteByPrimaryKey(Long dictId);

    /**
     * 插入字典 返回自增涨 主鍵
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
     long insert(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int insertSelective(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    List<SysDictionary> selectByExampleWithRowbounds(SysDictionaryCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    List<SysDictionary> selectByExample(SysDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    SysDictionary selectByPrimaryKey(Long dictId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysDictionary record, @Param("example") SysDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int updateByExample(@Param("record") SysDictionary record, @Param("example") SysDictionaryCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int updateByPrimaryKeySelective(SysDictionary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_dictionary
     *
     * @mbggenerated Sat Oct 06 11:52:46 CST 2018
     */
    int updateByPrimaryKey(SysDictionary record);

    /**
     * @param path 路径参数
     * @return 字典列表
     */
    // @Select(value = "SELECT * FROM sys_dictionary WHERE path like '#{path}%' and is_deleted = 0")
    List<SysDictionary> listSysDictionaryByPath(String path);
}