package com.epc.user.service.domain.purchaser;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class TPurchaserDetailInfoCriteria {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public TPurchaserDetailInfoCriteria() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdIsNull() {
            addCriterion("purchaser_id is null");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdIsNotNull() {
            addCriterion("purchaser_id is not null");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdEqualTo(Long value) {
            addCriterion("purchaser_id =", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdNotEqualTo(Long value) {
            addCriterion("purchaser_id <>", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdGreaterThan(Long value) {
            addCriterion("purchaser_id >", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdGreaterThanOrEqualTo(Long value) {
            addCriterion("purchaser_id >=", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdLessThan(Long value) {
            addCriterion("purchaser_id <", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdLessThanOrEqualTo(Long value) {
            addCriterion("purchaser_id <=", value, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdIn(List<Long> values) {
            addCriterion("purchaser_id in", values, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdNotIn(List<Long> values) {
            addCriterion("purchaser_id not in", values, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdBetween(Long value1, Long value2) {
            addCriterion("purchaser_id between", value1, value2, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andPurchaserIdNotBetween(Long value1, Long value2) {
            addCriterion("purchaser_id not between", value1, value2, "purchaserId");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIsNull() {
            addCriterion("uniform_credit_code is null");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIsNotNull() {
            addCriterion("uniform_credit_code is not null");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeEqualTo(String value) {
            addCriterion("uniform_credit_code =", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotEqualTo(String value) {
            addCriterion("uniform_credit_code <>", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeGreaterThan(String value) {
            addCriterion("uniform_credit_code >", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeGreaterThanOrEqualTo(String value) {
            addCriterion("uniform_credit_code >=", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLessThan(String value) {
            addCriterion("uniform_credit_code <", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLessThanOrEqualTo(String value) {
            addCriterion("uniform_credit_code <=", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeLike(String value) {
            addCriterion("uniform_credit_code like", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotLike(String value) {
            addCriterion("uniform_credit_code not like", value, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeIn(List<String> values) {
            addCriterion("uniform_credit_code in", values, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotIn(List<String> values) {
            addCriterion("uniform_credit_code not in", values, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeBetween(String value1, String value2) {
            addCriterion("uniform_credit_code between", value1, value2, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andUniformCreditCodeNotBetween(String value1, String value2) {
            addCriterion("uniform_credit_code not between", value1, value2, "uniformCreditCode");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameIsNull() {
            addCriterion("public_bank_name is null");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameIsNotNull() {
            addCriterion("public_bank_name is not null");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameEqualTo(String value) {
            addCriterion("public_bank_name =", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameNotEqualTo(String value) {
            addCriterion("public_bank_name <>", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameGreaterThan(String value) {
            addCriterion("public_bank_name >", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameGreaterThanOrEqualTo(String value) {
            addCriterion("public_bank_name >=", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameLessThan(String value) {
            addCriterion("public_bank_name <", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameLessThanOrEqualTo(String value) {
            addCriterion("public_bank_name <=", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameLike(String value) {
            addCriterion("public_bank_name like", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameNotLike(String value) {
            addCriterion("public_bank_name not like", value, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameIn(List<String> values) {
            addCriterion("public_bank_name in", values, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameNotIn(List<String> values) {
            addCriterion("public_bank_name not in", values, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameBetween(String value1, String value2) {
            addCriterion("public_bank_name between", value1, value2, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBankNameNotBetween(String value1, String value2) {
            addCriterion("public_bank_name not between", value1, value2, "publicBankName");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberIsNull() {
            addCriterion("public_ban_account_number is null");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberIsNotNull() {
            addCriterion("public_ban_account_number is not null");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberEqualTo(String value) {
            addCriterion("public_ban_account_number =", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberNotEqualTo(String value) {
            addCriterion("public_ban_account_number <>", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberGreaterThan(String value) {
            addCriterion("public_ban_account_number >", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberGreaterThanOrEqualTo(String value) {
            addCriterion("public_ban_account_number >=", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberLessThan(String value) {
            addCriterion("public_ban_account_number <", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberLessThanOrEqualTo(String value) {
            addCriterion("public_ban_account_number <=", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberLike(String value) {
            addCriterion("public_ban_account_number like", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberNotLike(String value) {
            addCriterion("public_ban_account_number not like", value, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberIn(List<String> values) {
            addCriterion("public_ban_account_number in", values, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberNotIn(List<String> values) {
            addCriterion("public_ban_account_number not in", values, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberBetween(String value1, String value2) {
            addCriterion("public_ban_account_number between", value1, value2, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andPublicBanAccountNumberNotBetween(String value1, String value2) {
            addCriterion("public_ban_account_number not between", value1, value2, "publicBanAccountNumber");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateIsNull() {
            addCriterion("\"qualification certificate\" is null");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateIsNotNull() {
            addCriterion("\"qualification certificate\" is not null");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateEqualTo(String value) {
            addCriterion("\"qualification certificate\" =", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateNotEqualTo(String value) {
            addCriterion("\"qualification certificate\" <>", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateGreaterThan(String value) {
            addCriterion("\"qualification certificate\" >", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateGreaterThanOrEqualTo(String value) {
            addCriterion("\"qualification certificate\" >=", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateLessThan(String value) {
            addCriterion("\"qualification certificate\" <", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateLessThanOrEqualTo(String value) {
            addCriterion("\"qualification certificate\" <=", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateLike(String value) {
            addCriterion("\"qualification certificate\" like", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateNotLike(String value) {
            addCriterion("\"qualification certificate\" not like", value, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateIn(List<String> values) {
            addCriterion("\"qualification certificate\" in", values, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateNotIn(List<String> values) {
            addCriterion("\"qualification certificate\" not in", values, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateBetween(String value1, String value2) {
            addCriterion("\"qualification certificate\" between", value1, value2, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andQualificationCertificateNotBetween(String value1, String value2) {
            addCriterion("\"qualification certificate\" not between", value1, value2, "qualificationCertificate");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNull() {
            addCriterion("business_license is null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIsNotNull() {
            addCriterion("business_license is not null");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseEqualTo(String value) {
            addCriterion("business_license =", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotEqualTo(String value) {
            addCriterion("business_license <>", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThan(String value) {
            addCriterion("business_license >", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseGreaterThanOrEqualTo(String value) {
            addCriterion("business_license >=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThan(String value) {
            addCriterion("business_license <", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLessThanOrEqualTo(String value) {
            addCriterion("business_license <=", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseLike(String value) {
            addCriterion("business_license like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotLike(String value) {
            addCriterion("business_license not like", value, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseIn(List<String> values) {
            addCriterion("business_license in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotIn(List<String> values) {
            addCriterion("business_license not in", values, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseBetween(String value1, String value2) {
            addCriterion("business_license between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andBusinessLicenseNotBetween(String value1, String value2) {
            addCriterion("business_license not between", value1, value2, "businessLicense");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveIsNull() {
            addCriterion("legal_idcard_positive is null");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveIsNotNull() {
            addCriterion("legal_idcard_positive is not null");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveEqualTo(String value) {
            addCriterion("legal_idcard_positive =", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveNotEqualTo(String value) {
            addCriterion("legal_idcard_positive <>", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveGreaterThan(String value) {
            addCriterion("legal_idcard_positive >", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveGreaterThanOrEqualTo(String value) {
            addCriterion("legal_idcard_positive >=", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveLessThan(String value) {
            addCriterion("legal_idcard_positive <", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveLessThanOrEqualTo(String value) {
            addCriterion("legal_idcard_positive <=", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveLike(String value) {
            addCriterion("legal_idcard_positive like", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveNotLike(String value) {
            addCriterion("legal_idcard_positive not like", value, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveIn(List<String> values) {
            addCriterion("legal_idcard_positive in", values, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveNotIn(List<String> values) {
            addCriterion("legal_idcard_positive not in", values, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveBetween(String value1, String value2) {
            addCriterion("legal_idcard_positive between", value1, value2, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardPositiveNotBetween(String value1, String value2) {
            addCriterion("legal_idcard_positive not between", value1, value2, "legalIdcardPositive");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherIsNull() {
            addCriterion("legal_idcard_other is null");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherIsNotNull() {
            addCriterion("legal_idcard_other is not null");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherEqualTo(String value) {
            addCriterion("legal_idcard_other =", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherNotEqualTo(String value) {
            addCriterion("legal_idcard_other <>", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherGreaterThan(String value) {
            addCriterion("legal_idcard_other >", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherGreaterThanOrEqualTo(String value) {
            addCriterion("legal_idcard_other >=", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherLessThan(String value) {
            addCriterion("legal_idcard_other <", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherLessThanOrEqualTo(String value) {
            addCriterion("legal_idcard_other <=", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherLike(String value) {
            addCriterion("legal_idcard_other like", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherNotLike(String value) {
            addCriterion("legal_idcard_other not like", value, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherIn(List<String> values) {
            addCriterion("legal_idcard_other in", values, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherNotIn(List<String> values) {
            addCriterion("legal_idcard_other not in", values, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherBetween(String value1, String value2) {
            addCriterion("legal_idcard_other between", value1, value2, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andLegalIdcardOtherNotBetween(String value1, String value2) {
            addCriterion("legal_idcard_other not between", value1, value2, "legalIdcardOther");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationIsNull() {
            addCriterion("certificate_of_authorization is null");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationIsNotNull() {
            addCriterion("certificate_of_authorization is not null");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationEqualTo(String value) {
            addCriterion("certificate_of_authorization =", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationNotEqualTo(String value) {
            addCriterion("certificate_of_authorization <>", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationGreaterThan(String value) {
            addCriterion("certificate_of_authorization >", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationGreaterThanOrEqualTo(String value) {
            addCriterion("certificate_of_authorization >=", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationLessThan(String value) {
            addCriterion("certificate_of_authorization <", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationLessThanOrEqualTo(String value) {
            addCriterion("certificate_of_authorization <=", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationLike(String value) {
            addCriterion("certificate_of_authorization like", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationNotLike(String value) {
            addCriterion("certificate_of_authorization not like", value, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationIn(List<String> values) {
            addCriterion("certificate_of_authorization in", values, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationNotIn(List<String> values) {
            addCriterion("certificate_of_authorization not in", values, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationBetween(String value1, String value2) {
            addCriterion("certificate_of_authorization between", value1, value2, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andCertificateOfAuthorizationNotBetween(String value1, String value2) {
            addCriterion("certificate_of_authorization not between", value1, value2, "certificateOfAuthorization");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontIsNull() {
            addCriterion("operator_id_card_front is null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontIsNotNull() {
            addCriterion("operator_id_card_front is not null");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontEqualTo(String value) {
            addCriterion("operator_id_card_front =", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontNotEqualTo(String value) {
            addCriterion("operator_id_card_front <>", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontGreaterThan(String value) {
            addCriterion("operator_id_card_front >", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontGreaterThanOrEqualTo(String value) {
            addCriterion("operator_id_card_front >=", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontLessThan(String value) {
            addCriterion("operator_id_card_front <", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontLessThanOrEqualTo(String value) {
            addCriterion("operator_id_card_front <=", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontLike(String value) {
            addCriterion("operator_id_card_front like", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontNotLike(String value) {
            addCriterion("operator_id_card_front not like", value, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontIn(List<String> values) {
            addCriterion("operator_id_card_front in", values, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontNotIn(List<String> values) {
            addCriterion("operator_id_card_front not in", values, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontBetween(String value1, String value2) {
            addCriterion("operator_id_card_front between", value1, value2, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andOperatorIdCardFrontNotBetween(String value1, String value2) {
            addCriterion("operator_id_card_front not between", value1, value2, "operatorIdCardFront");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldIsNull() {
            addCriterion("extended_field is null");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldIsNotNull() {
            addCriterion("extended_field is not null");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldEqualTo(String value) {
            addCriterion("extended_field =", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldNotEqualTo(String value) {
            addCriterion("extended_field <>", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldGreaterThan(String value) {
            addCriterion("extended_field >", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldGreaterThanOrEqualTo(String value) {
            addCriterion("extended_field >=", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldLessThan(String value) {
            addCriterion("extended_field <", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldLessThanOrEqualTo(String value) {
            addCriterion("extended_field <=", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldLike(String value) {
            addCriterion("extended_field like", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldNotLike(String value) {
            addCriterion("extended_field not like", value, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldIn(List<String> values) {
            addCriterion("extended_field in", values, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldNotIn(List<String> values) {
            addCriterion("extended_field not in", values, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldBetween(String value1, String value2) {
            addCriterion("extended_field between", value1, value2, "extendedField");
            return (Criteria) this;
        }

        public Criteria andExtendedFieldNotBetween(String value1, String value2) {
            addCriterion("extended_field not between", value1, value2, "extendedField");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNull() {
            addCriterion("create_at is null");
            return (Criteria) this;
        }

        public Criteria andCreateAtIsNotNull() {
            addCriterion("create_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreateAtEqualTo(Date value) {
            addCriterion("create_at =", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotEqualTo(Date value) {
            addCriterion("create_at <>", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThan(Date value) {
            addCriterion("create_at >", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("create_at >=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThan(Date value) {
            addCriterion("create_at <", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtLessThanOrEqualTo(Date value) {
            addCriterion("create_at <=", value, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtIn(List<Date> values) {
            addCriterion("create_at in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotIn(List<Date> values) {
            addCriterion("create_at not in", values, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtBetween(Date value1, Date value2) {
            addCriterion("create_at between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andCreateAtNotBetween(Date value1, Date value2) {
            addCriterion("create_at not between", value1, value2, "createAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNull() {
            addCriterion("update_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIsNotNull() {
            addCriterion("update_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdateAtEqualTo(Date value) {
            addCriterion("update_at =", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotEqualTo(Date value) {
            addCriterion("update_at <>", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThan(Date value) {
            addCriterion("update_at >", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtGreaterThanOrEqualTo(Date value) {
            addCriterion("update_at >=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThan(Date value) {
            addCriterion("update_at <", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtLessThanOrEqualTo(Date value) {
            addCriterion("update_at <=", value, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtIn(List<Date> values) {
            addCriterion("update_at in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotIn(List<Date> values) {
            addCriterion("update_at not in", values, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtBetween(Date value1, Date value2) {
            addCriterion("update_at between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andUpdateAtNotBetween(Date value1, Date value2) {
            addCriterion("update_at not between", value1, value2, "updateAt");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNull() {
            addCriterion("is_deleted is null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIsNotNull() {
            addCriterion("is_deleted is not null");
            return (Criteria) this;
        }

        public Criteria andIsDeletedEqualTo(Integer value) {
            addCriterion("is_deleted =", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotEqualTo(Integer value) {
            addCriterion("is_deleted <>", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThan(Integer value) {
            addCriterion("is_deleted >", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedGreaterThanOrEqualTo(Integer value) {
            addCriterion("is_deleted >=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThan(Integer value) {
            addCriterion("is_deleted <", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedLessThanOrEqualTo(Integer value) {
            addCriterion("is_deleted <=", value, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedIn(List<Integer> values) {
            addCriterion("is_deleted in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotIn(List<Integer> values) {
            addCriterion("is_deleted not in", values, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted between", value1, value2, "isDeleted");
            return (Criteria) this;
        }

        public Criteria andIsDeletedNotBetween(Integer value1, Integer value2) {
            addCriterion("is_deleted not between", value1, value2, "isDeleted");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated do_not_delete_during_merge Tue Sep 11 16:21:27 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table t_purchaser_detail_info
     *
     * @mbggenerated Tue Sep 11 16:21:27 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}