package com.epc.web.service.domain.supplier;

import java.io.Serializable;
import java.util.Date;

public class BSignUp implements Serializable {

    private Long id;

    private Long projectId;

    private Long procurementProjectId;

    private String bidsId;


    private String bidsName;


    private String bidsCode;

    private Long supplierId;


    private String supplierName;

    private Long userId;


    private Date createAt;


    private Date updateAt;

    private Integer isDeleted;

    private static final long serialVersionUID = 1L;


    public Long getId() {
        return id;
    }


    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.project_id
     *
     * @return the value of b_sign_up.project_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.project_id
     *
     * @param projectId the value for b_sign_up.project_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.procurement_project_id
     *
     * @return the value of b_sign_up.procurement_project_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Long getProcurementProjectId() {
        return procurementProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.procurement_project_id
     *
     * @param procurementProjectId the value for b_sign_up.procurement_project_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setProcurementProjectId(Long procurementProjectId) {
        this.procurementProjectId = procurementProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.bids_id
     *
     * @return the value of b_sign_up.bids_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public String getBidsId() {
        return bidsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.bids_id
     *
     * @param bidsId the value for b_sign_up.bids_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setBidsId(String bidsId) {
        this.bidsId = bidsId == null ? null : bidsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.bids_name
     *
     * @return the value of b_sign_up.bids_name
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public String getBidsName() {
        return bidsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.bids_name
     *
     * @param bidsName the value for b_sign_up.bids_name
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setBidsName(String bidsName) {
        this.bidsName = bidsName == null ? null : bidsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.bids_code
     *
     * @return the value of b_sign_up.bids_code
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public String getBidsCode() {
        return bidsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.bids_code
     *
     * @param bidsCode the value for b_sign_up.bids_code
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setBidsCode(String bidsCode) {
        this.bidsCode = bidsCode == null ? null : bidsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.supplier_id
     *
     * @return the value of b_sign_up.supplier_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.supplier_id
     *
     * @param supplierId the value for b_sign_up.supplier_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.supplier_name
     *
     * @return the value of b_sign_up.supplier_name
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.supplier_name
     *
     * @param supplierName the value for b_sign_up.supplier_name
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.user_id
     *
     * @return the value of b_sign_up.user_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.user_id
     *
     * @param userId the value for b_sign_up.user_id
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.create_at
     *
     * @return the value of b_sign_up.create_at
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.create_at
     *
     * @param createAt the value for b_sign_up.create_at
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.update_at
     *
     * @return the value of b_sign_up.update_at
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.update_at
     *
     * @param updateAt the value for b_sign_up.update_at
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_sign_up.is_deleted
     *
     * @return the value of b_sign_up.is_deleted
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_sign_up.is_deleted
     *
     * @param isDeleted the value for b_sign_up.is_deleted
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", procurementProjectId=").append(procurementProjectId);
        sb.append(", bidsId=").append(bidsId);
        sb.append(", bidsName=").append(bidsName);
        sb.append(", bidsCode=").append(bidsCode);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", userId=").append(userId);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}