package com.epc.web.service.domain.supplier;

import java.io.Serializable;
import java.util.Date;

public class TProjectProcedure implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Long projectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.purchase_project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Long purchaseProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.procedure_code
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private String procedureCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.operate_type
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private String operateType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.creator
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private String creator;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.create_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.update_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.is_end
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Integer isEnd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_project_procedure.is_deleted
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_project_procedure
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.id
     *
     * @return the value of t_project_procedure.id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.id
     *
     * @param id the value for t_project_procedure.id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.project_id
     *
     * @return the value of t_project_procedure.project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Long getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.project_id
     *
     * @param projectId the value for t_project_procedure.project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setProjectId(Long projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.purchase_project_id
     *
     * @return the value of t_project_procedure.purchase_project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Long getPurchaseProjectId() {
        return purchaseProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.purchase_project_id
     *
     * @param purchaseProjectId the value for t_project_procedure.purchase_project_id
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setPurchaseProjectId(Long purchaseProjectId) {
        this.purchaseProjectId = purchaseProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.procedure_code
     *
     * @return the value of t_project_procedure.procedure_code
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public String getProcedureCode() {
        return procedureCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.procedure_code
     *
     * @param procedureCode the value for t_project_procedure.procedure_code
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setProcedureCode(String procedureCode) {
        this.procedureCode = procedureCode == null ? null : procedureCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.operate_type
     *
     * @return the value of t_project_procedure.operate_type
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public String getOperateType() {
        return operateType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.operate_type
     *
     * @param operateType the value for t_project_procedure.operate_type
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setOperateType(String operateType) {
        this.operateType = operateType == null ? null : operateType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.creator
     *
     * @return the value of t_project_procedure.creator
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.creator
     *
     * @param creator the value for t_project_procedure.creator
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.create_at
     *
     * @return the value of t_project_procedure.create_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.create_at
     *
     * @param createAt the value for t_project_procedure.create_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.update_at
     *
     * @return the value of t_project_procedure.update_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.update_at
     *
     * @param updateAt the value for t_project_procedure.update_at
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.is_end
     *
     * @return the value of t_project_procedure.is_end
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Integer getIsEnd() {
        return isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.is_end
     *
     * @param isEnd the value for t_project_procedure.is_end
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setIsEnd(Integer isEnd) {
        this.isEnd = isEnd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_project_procedure.is_deleted
     *
     * @return the value of t_project_procedure.is_deleted
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_project_procedure.is_deleted
     *
     * @param isDeleted the value for t_project_procedure.is_deleted
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_procedure
     *
     * @mbggenerated Fri Oct 12 11:54:17 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", projectId=").append(projectId);
        sb.append(", purchaseProjectId=").append(purchaseProjectId);
        sb.append(", procedureCode=").append(procedureCode);
        sb.append(", operateType=").append(operateType);
        sb.append(", creator=").append(creator);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isEnd=").append(isEnd);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}