package com.epc.web.service.domain.supplier;

import java.io.Serializable;
import java.util.Date;

public class TSupplierSign implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.procurement_project_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Long procurementProjectId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.bids_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Long bidsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.bids_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private String bidsName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.company_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Long companyId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.company_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private String companyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.person_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private String personName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.identit_card
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private String identitCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.cellphone
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.create_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.update_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_supplier_sign.is_deleted
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.id
     *
     * @return the value of t_supplier_sign.id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.id
     *
     * @param id the value for t_supplier_sign.id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.procurement_project_id
     *
     * @return the value of t_supplier_sign.procurement_project_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Long getProcurementProjectId() {
        return procurementProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.procurement_project_id
     *
     * @param procurementProjectId the value for t_supplier_sign.procurement_project_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setProcurementProjectId(Long procurementProjectId) {
        this.procurementProjectId = procurementProjectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.bids_id
     *
     * @return the value of t_supplier_sign.bids_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Long getBidsId() {
        return bidsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.bids_id
     *
     * @param bidsId the value for t_supplier_sign.bids_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setBidsId(Long bidsId) {
        this.bidsId = bidsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.bids_name
     *
     * @return the value of t_supplier_sign.bids_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public String getBidsName() {
        return bidsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.bids_name
     *
     * @param bidsName the value for t_supplier_sign.bids_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setBidsName(String bidsName) {
        this.bidsName = bidsName == null ? null : bidsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.company_id
     *
     * @return the value of t_supplier_sign.company_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.company_id
     *
     * @param companyId the value for t_supplier_sign.company_id
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.company_name
     *
     * @return the value of t_supplier_sign.company_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public String getCompanyName() {
        return companyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.company_name
     *
     * @param companyName the value for t_supplier_sign.company_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setCompanyName(String companyName) {
        this.companyName = companyName == null ? null : companyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.person_name
     *
     * @return the value of t_supplier_sign.person_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public String getPersonName() {
        return personName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.person_name
     *
     * @param personName the value for t_supplier_sign.person_name
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setPersonName(String personName) {
        this.personName = personName == null ? null : personName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.identit_card
     *
     * @return the value of t_supplier_sign.identit_card
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public String getIdentitCard() {
        return identitCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.identit_card
     *
     * @param identitCard the value for t_supplier_sign.identit_card
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setIdentitCard(String identitCard) {
        this.identitCard = identitCard == null ? null : identitCard.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.cellphone
     *
     * @return the value of t_supplier_sign.cellphone
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.cellphone
     *
     * @param cellphone the value for t_supplier_sign.cellphone
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.create_at
     *
     * @return the value of t_supplier_sign.create_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.create_at
     *
     * @param createAt the value for t_supplier_sign.create_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.update_at
     *
     * @return the value of t_supplier_sign.update_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.update_at
     *
     * @param updateAt the value for t_supplier_sign.update_at
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_supplier_sign.is_deleted
     *
     * @return the value of t_supplier_sign.is_deleted
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_supplier_sign.is_deleted
     *
     * @param isDeleted the value for t_supplier_sign.is_deleted
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", procurementProjectId=").append(procurementProjectId);
        sb.append(", bidsId=").append(bidsId);
        sb.append(", bidsName=").append(bidsName);
        sb.append(", companyId=").append(companyId);
        sb.append(", companyName=").append(companyName);
        sb.append(", personName=").append(personName);
        sb.append(", identitCard=").append(identitCard);
        sb.append(", cellphone=").append(cellphone);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}