package com.epc.web.service.mapper.operator;

import com.epc.web.service.domain.operator.TOperatorPurchaser;
import com.epc.web.service.domain.operator.TOperatorPurchaserCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TOperatorPurchaserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int countByExample(TOperatorPurchaserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int deleteByExample(TOperatorPurchaserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int insert(TOperatorPurchaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int insertSelective(TOperatorPurchaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    List<TOperatorPurchaser> selectByExampleWithRowbounds(TOperatorPurchaserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    List<TOperatorPurchaser> selectByExample(TOperatorPurchaserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    TOperatorPurchaser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int updateByExampleSelective(@Param("record") TOperatorPurchaser record, @Param("example") TOperatorPurchaserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int updateByExample(@Param("record") TOperatorPurchaser record, @Param("example") TOperatorPurchaserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int updateByPrimaryKeySelective(TOperatorPurchaser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_purchaser
     *
     * @mbggenerated Thu Sep 13 12:00:29 CST 2018
     */
    int updateByPrimaryKey(TOperatorPurchaser record);
}