package com.epc.platform.service.domain.admin;

import java.io.Serializable;
import java.util.Date;

public class SysAdminUserOperator implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.admin_user_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Long adminUserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.admin_user_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private String adminUserName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.operator_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Long operatorId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.comany_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private String comanyName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.create_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.update_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user_operator.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_admin_user_operator
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.id
     *
     * @return the value of sys_admin_user_operator.id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.id
     *
     * @param id the value for sys_admin_user_operator.id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.admin_user_id
     *
     * @return the value of sys_admin_user_operator.admin_user_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Long getAdminUserId() {
        return adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.admin_user_id
     *
     * @param adminUserId the value for sys_admin_user_operator.admin_user_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setAdminUserId(Long adminUserId) {
        this.adminUserId = adminUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.admin_user_name
     *
     * @return the value of sys_admin_user_operator.admin_user_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public String getAdminUserName() {
        return adminUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.admin_user_name
     *
     * @param adminUserName the value for sys_admin_user_operator.admin_user_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setAdminUserName(String adminUserName) {
        this.adminUserName = adminUserName == null ? null : adminUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.operator_id
     *
     * @return the value of sys_admin_user_operator.operator_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Long getOperatorId() {
        return operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.operator_id
     *
     * @param operatorId the value for sys_admin_user_operator.operator_id
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setOperatorId(Long operatorId) {
        this.operatorId = operatorId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.comany_name
     *
     * @return the value of sys_admin_user_operator.comany_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public String getComanyName() {
        return comanyName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.comany_name
     *
     * @param comanyName the value for sys_admin_user_operator.comany_name
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setComanyName(String comanyName) {
        this.comanyName = comanyName == null ? null : comanyName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.create_at
     *
     * @return the value of sys_admin_user_operator.create_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.create_at
     *
     * @param createAt the value for sys_admin_user_operator.create_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.update_at
     *
     * @return the value of sys_admin_user_operator.update_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.update_at
     *
     * @param updateAt the value for sys_admin_user_operator.update_at
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user_operator.is_deleted
     *
     * @return the value of sys_admin_user_operator.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user_operator.is_deleted
     *
     * @param isDeleted the value for sys_admin_user_operator.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_operator
     *
     * @mbggenerated Mon Sep 10 16:52:31 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", adminUserId=").append(adminUserId);
        sb.append(", adminUserName=").append(adminUserName);
        sb.append(", operatorId=").append(operatorId);
        sb.append(", comanyName=").append(comanyName);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}