package com.epc.platform.service.domain.admin;

import java.io.Serializable;
import java.util.Date;

public class SysAdminRoleResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.amdin_role_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Long amdinRoleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.admin_resource_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Long adminResourceId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_role_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.id
     *
     * @return the value of sys_admin_role_resource.id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.id
     *
     * @param id the value for sys_admin_role_resource.id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.amdin_role_id
     *
     * @return the value of sys_admin_role_resource.amdin_role_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Long getAmdinRoleId() {
        return amdinRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.amdin_role_id
     *
     * @param amdinRoleId the value for sys_admin_role_resource.amdin_role_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setAmdinRoleId(Long amdinRoleId) {
        this.amdinRoleId = amdinRoleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.admin_resource_id
     *
     * @return the value of sys_admin_role_resource.admin_resource_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Long getAdminResourceId() {
        return adminResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.admin_resource_id
     *
     * @param adminResourceId the value for sys_admin_role_resource.admin_resource_id
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setAdminResourceId(Long adminResourceId) {
        this.adminResourceId = adminResourceId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.create_at
     *
     * @return the value of sys_admin_role_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.create_at
     *
     * @param createAt the value for sys_admin_role_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.update_at
     *
     * @return the value of sys_admin_role_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.update_at
     *
     * @param updateAt the value for sys_admin_role_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_role_resource.is_deleted
     *
     * @return the value of sys_admin_role_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_role_resource.is_deleted
     *
     * @param isDeleted the value for sys_admin_role_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", amdinRoleId=").append(amdinRoleId);
        sb.append(", adminResourceId=").append(adminResourceId);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}