package com.epc.platform.service.domain.admin;

import java.io.Serializable;
import java.util.Date;

public class SysAdminUser implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.id
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.name
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.phone
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.password
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_user.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_admin_user
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.id
     *
     * @return the value of sys_admin_user.id
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.id
     *
     * @param id the value for sys_admin_user.id
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.name
     *
     * @return the value of sys_admin_user.name
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.name
     *
     * @param name the value for sys_admin_user.name
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.phone
     *
     * @return the value of sys_admin_user.phone
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.phone
     *
     * @param phone the value for sys_admin_user.phone
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.password
     *
     * @return the value of sys_admin_user.password
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.password
     *
     * @param password the value for sys_admin_user.password
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.create_at
     *
     * @return the value of sys_admin_user.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.create_at
     *
     * @param createAt the value for sys_admin_user.create_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.update_at
     *
     * @return the value of sys_admin_user.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.update_at
     *
     * @param updateAt the value for sys_admin_user.update_at
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_user.is_deleted
     *
     * @return the value of sys_admin_user.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_user.is_deleted
     *
     * @param isDeleted the value for sys_admin_user.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user
     *
     * @mbggenerated Mon Sep 10 16:51:58 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", phone=").append(phone);
        sb.append(", password=").append(password);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}