package com.epc.platform.service.domain.admin;

import java.io.Serializable;
import java.util.Date;

public class SysAdminResource implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.parent_id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private Long parentId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.name
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.title
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.type
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private String type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.url
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private String url;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sys_admin_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sys_admin_resource
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.id
     *
     * @return the value of sys_admin_resource.id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.id
     *
     * @param id the value for sys_admin_resource.id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.parent_id
     *
     * @return the value of sys_admin_resource.parent_id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public Long getParentId() {
        return parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.parent_id
     *
     * @param parentId the value for sys_admin_resource.parent_id
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setParentId(Long parentId) {
        this.parentId = parentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.name
     *
     * @return the value of sys_admin_resource.name
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.name
     *
     * @param name the value for sys_admin_resource.name
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.title
     *
     * @return the value of sys_admin_resource.title
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.title
     *
     * @param title the value for sys_admin_resource.title
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.type
     *
     * @return the value of sys_admin_resource.type
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.type
     *
     * @param type the value for sys_admin_resource.type
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.url
     *
     * @return the value of sys_admin_resource.url
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.url
     *
     * @param url the value for sys_admin_resource.url
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.create_at
     *
     * @return the value of sys_admin_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.create_at
     *
     * @param createAt the value for sys_admin_resource.create_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.update_at
     *
     * @return the value of sys_admin_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.update_at
     *
     * @param updateAt the value for sys_admin_resource.update_at
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sys_admin_resource.is_deleted
     *
     * @return the value of sys_admin_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sys_admin_resource.is_deleted
     *
     * @param isDeleted the value for sys_admin_resource.is_deleted
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_resource
     *
     * @mbggenerated Mon Sep 10 16:49:57 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", parentId=").append(parentId);
        sb.append(", name=").append(name);
        sb.append(", title=").append(title);
        sb.append(", type=").append(type);
        sb.append(", url=").append(url);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}