package com.epc.web.service.domain.purchaser;

import java.io.Serializable;
import java.util.Date;

public class TPurchaserAgency implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.cellphone
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.password
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.state
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.supplier_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Long supplierId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.supplier_name
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private String supplierName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.purchaser_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private String purchaserId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.source
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private String source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.create_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.update_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_purchaser_agency.is_deleted
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.id
     *
     * @return the value of t_purchaser_agency.id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.id
     *
     * @param id the value for t_purchaser_agency.id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.cellphone
     *
     * @return the value of t_purchaser_agency.cellphone
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.cellphone
     *
     * @param cellphone the value for t_purchaser_agency.cellphone
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.password
     *
     * @return the value of t_purchaser_agency.password
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.password
     *
     * @param password the value for t_purchaser_agency.password
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.state
     *
     * @return the value of t_purchaser_agency.state
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.state
     *
     * @param state the value for t_purchaser_agency.state
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.supplier_id
     *
     * @return the value of t_purchaser_agency.supplier_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Long getSupplierId() {
        return supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.supplier_id
     *
     * @param supplierId the value for t_purchaser_agency.supplier_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setSupplierId(Long supplierId) {
        this.supplierId = supplierId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.supplier_name
     *
     * @return the value of t_purchaser_agency.supplier_name
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public String getSupplierName() {
        return supplierName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.supplier_name
     *
     * @param supplierName the value for t_purchaser_agency.supplier_name
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setSupplierName(String supplierName) {
        this.supplierName = supplierName == null ? null : supplierName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.purchaser_id
     *
     * @return the value of t_purchaser_agency.purchaser_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public String getPurchaserId() {
        return purchaserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.purchaser_id
     *
     * @param purchaserId the value for t_purchaser_agency.purchaser_id
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setPurchaserId(String purchaserId) {
        this.purchaserId = purchaserId == null ? null : purchaserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.source
     *
     * @return the value of t_purchaser_agency.source
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.source
     *
     * @param source the value for t_purchaser_agency.source
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.create_at
     *
     * @return the value of t_purchaser_agency.create_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.create_at
     *
     * @param createAt the value for t_purchaser_agency.create_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.update_at
     *
     * @return the value of t_purchaser_agency.update_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.update_at
     *
     * @param updateAt the value for t_purchaser_agency.update_at
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_purchaser_agency.is_deleted
     *
     * @return the value of t_purchaser_agency.is_deleted
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_purchaser_agency.is_deleted
     *
     * @param isDeleted the value for t_purchaser_agency.is_deleted
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", cellphone=").append(cellphone);
        sb.append(", password=").append(password);
        sb.append(", state=").append(state);
        sb.append(", supplierId=").append(supplierId);
        sb.append(", supplierName=").append(supplierName);
        sb.append(", purchaserId=").append(purchaserId);
        sb.append(", source=").append(source);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}