package com.epc.web.service.mapper.purchaser;

import com.epc.web.service.domain.purchaser.TPurchaserAgency;
import com.epc.web.service.domain.purchaser.TPurchaserAgencyCriteria;
import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TPurchaserAgencyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int countByExample(TPurchaserAgencyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int deleteByExample(TPurchaserAgencyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int insert(TPurchaserAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int insertSelective(TPurchaserAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    List<TPurchaserAgency> selectByExampleWithRowbounds(TPurchaserAgencyCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    List<TPurchaserAgency> selectByExample(TPurchaserAgencyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    TPurchaserAgency selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TPurchaserAgency record, @Param("example") TPurchaserAgencyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int updateByExample(@Param("record") TPurchaserAgency record, @Param("example") TPurchaserAgencyCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int updateByPrimaryKeySelective(TPurchaserAgency record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_agency
     *
     * @mbggenerated Thu Sep 13 13:52:50 CST 2018
     */
    int updateByPrimaryKey(TPurchaserAgency record);
}