package com.epc.web.service.mapper.agency;

import com.epc.web.facade.agency.vo.AgencyEmployeeVo;
import com.epc.web.facade.loginuser.dto.LoginUser;
import com.epc.web.service.domain.agency.TAgencyBasicInfo;
import com.epc.web.service.domain.agency.TAgencyBasicInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAgencyBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int countByExample(TAgencyBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int deleteByExample(TAgencyBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int insert(TAgencyBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int insertSelective(TAgencyBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    List<TAgencyBasicInfo> selectByExampleWithRowbounds(TAgencyBasicInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    List<TAgencyBasicInfo> selectByExample(TAgencyBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    TAgencyBasicInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int updateByExampleSelective(@Param("record") TAgencyBasicInfo record, @Param("example") TAgencyBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int updateByExample(@Param("record") TAgencyBasicInfo record, @Param("example") TAgencyBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int updateByPrimaryKeySelective(TAgencyBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_basic_info
     *
     * @mbggenerated Thu Sep 13 16:23:51 CST 2018
     */
    int updateByPrimaryKey(TAgencyBasicInfo record);

    LoginUser login(@Param("cellphone") String cellphone, @Param("pwd") String pwd);

    AgencyEmployeeVo queryEmployeeByCellphone(String cellphone);

    AgencyEmployeeVo queryEmployeeById(Long id);
}