package com.epc.web.service.mapper.agency;

import com.epc.web.service.domain.agency.TAgencySupplier;
import com.epc.web.service.domain.agency.TAgencySupplierCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAgencySupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int countByExample(TAgencySupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int deleteByExample(TAgencySupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int insert(TAgencySupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int insertSelective(TAgencySupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    List<TAgencySupplier> selectByExampleWithRowbounds(TAgencySupplierCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    List<TAgencySupplier> selectByExample(TAgencySupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    TAgencySupplier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") TAgencySupplier record, @Param("example") TAgencySupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int updateByExample(@Param("record") TAgencySupplier record, @Param("example") TAgencySupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int updateByPrimaryKeySelective(TAgencySupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_supplier
     *
     * @mbggenerated Fri Sep 14 19:58:08 CST 2018
     */
    int updateByPrimaryKey(TAgencySupplier record);
}