package com.epc.web.service.mapper.agency;

import com.epc.web.service.domain.agency.TAgencyAttachment;
import com.epc.web.service.domain.agency.TAgencyAttachmentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TAgencyAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int countByExample(TAgencyAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int deleteByExample(TAgencyAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int insert(TAgencyAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int insertSelective(TAgencyAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    List<TAgencyAttachment> selectByExampleWithRowbounds(TAgencyAttachmentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    List<TAgencyAttachment> selectByExample(TAgencyAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    TAgencyAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int updateByExampleSelective(@Param("record") TAgencyAttachment record, @Param("example") TAgencyAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int updateByExample(@Param("record") TAgencyAttachment record, @Param("example") TAgencyAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int updateByPrimaryKeySelective(TAgencyAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_agency_attachment
     *
     * @mbggenerated Thu Sep 13 21:06:35 CST 2018
     */
    int updateByPrimaryKey(TAgencyAttachment record);
}