package com.epc.platform.service.mapper.operator;

import com.epc.platform.service.domain.operator.TOperatorAttachment;
import com.epc.platform.service.domain.operator.TOperatorAttachmentCriteria;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

import java.util.List;

public interface TOperatorAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int countByExample(TOperatorAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int deleteByExample(TOperatorAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int insert(TOperatorAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int insertSelective(TOperatorAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    List<TOperatorAttachment> selectByExampleWithRowbounds(TOperatorAttachmentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    List<TOperatorAttachment> selectByExample(TOperatorAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    TOperatorAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int updateByExampleSelective(@Param("record") TOperatorAttachment record, @Param("example") TOperatorAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int updateByExample(@Param("record") TOperatorAttachment record, @Param("example") TOperatorAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int updateByPrimaryKeySelective(TOperatorAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_attachment
     *
     * @mbggenerated Wed Sep 12 11:44:31 CST 2018
     */
    int updateByPrimaryKey(TOperatorAttachment record);
}