package com.epc.user.service.mapper.purchaser;

import com.epc.user.service.domain.purchaser.TPurchaserUser;
import com.epc.user.service.domain.purchaser.TPurchaserUserCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TPurchaserUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int countByExample(TPurchaserUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int deleteByExample(TPurchaserUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int insert(TPurchaserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int insertSelective(TPurchaserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    List<TPurchaserUser> selectByExampleWithRowbounds(TPurchaserUserCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    List<TPurchaserUser> selectByExample(TPurchaserUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    TPurchaserUser selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int updateByExampleSelective(@Param("record") TPurchaserUser record, @Param("example") TPurchaserUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int updateByExample(@Param("record") TPurchaserUser record, @Param("example") TPurchaserUserCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int updateByPrimaryKeySelective(TPurchaserUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_user
     *
     * @mbggenerated Tue Sep 11 16:20:16 CST 2018
     */
    int updateByPrimaryKey(TPurchaserUser record);
}