package com.epc.platform.service.mapper.reviewexpertr;

import com.epc.platform.service.domain.reviewexpertr.TExpertAttachment;
import com.epc.platform.service.domain.reviewexpertr.TExpertAttachmentCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TExpertAttachmentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int countByExample(TExpertAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int deleteByExample(TExpertAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int insert(TExpertAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int insertSelective(TExpertAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    List<TExpertAttachment> selectByExampleWithRowbounds(TExpertAttachmentCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    List<TExpertAttachment> selectByExample(TExpertAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    TExpertAttachment selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TExpertAttachment record, @Param("example") TExpertAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByExample(@Param("record") TExpertAttachment record, @Param("example") TExpertAttachmentCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByPrimaryKeySelective(TExpertAttachment record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_attachment
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByPrimaryKey(TExpertAttachment record);
}