package com.epc.platform.service.mapper.reviewexpertr;

import com.epc.platform.service.domain.reviewexpertr.TExpertDetailInfo;
import com.epc.platform.service.domain.reviewexpertr.TExpertDetailInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TExpertDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int countByExample(TExpertDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int deleteByExample(TExpertDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int insert(TExpertDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int insertSelective(TExpertDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    List<TExpertDetailInfo> selectByExampleWithRowbounds(TExpertDetailInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    List<TExpertDetailInfo> selectByExample(TExpertDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    TExpertDetailInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByExampleSelective(@Param("record") TExpertDetailInfo record, @Param("example") TExpertDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByExample(@Param("record") TExpertDetailInfo record, @Param("example") TExpertDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByPrimaryKeySelective(TExpertDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_detail_info
     *
     * @mbggenerated Fri Sep 14 16:35:24 CST 2018
     */
    int updateByPrimaryKey(TExpertDetailInfo record);
}