package com.epc.user.service.mapper.purchaser;

import com.epc.user.service.domain.purchaser.TPurchaserSupplier;
import com.epc.user.service.domain.purchaser.TPurchaserSupplierCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TPurchaserSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int countByExample(TPurchaserSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int deleteByExample(TPurchaserSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int insert(TPurchaserSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int insertSelective(TPurchaserSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    List<TPurchaserSupplier> selectByExampleWithRowbounds(TPurchaserSupplierCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    List<TPurchaserSupplier> selectByExample(TPurchaserSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    TPurchaserSupplier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int updateByExampleSelective(@Param("record") TPurchaserSupplier record, @Param("example") TPurchaserSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int updateByExample(@Param("record") TPurchaserSupplier record, @Param("example") TPurchaserSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int updateByPrimaryKeySelective(TPurchaserSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_purchaser_supplier
     *
     * @mbggenerated Thu Sep 13 13:26:06 CST 2018
     */
    int updateByPrimaryKey(TPurchaserSupplier record);
}