package com.epc.tendering.service.mapper.project;

import com.epc.tendering.service.domain.project.TProjectBasicInfo;
import com.epc.tendering.service.domain.project.TProjectBasicInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TProjectBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int countByExample(TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int deleteByExample(TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int insert(TProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int insertSelective(TProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    List<TProjectBasicInfo> selectByExampleWithBLOBsWithRowbounds(TProjectBasicInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    List<TProjectBasicInfo> selectByExampleWithBLOBs(TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    List<TProjectBasicInfo> selectByExampleWithRowbounds(TProjectBasicInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    List<TProjectBasicInfo> selectByExample(TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    TProjectBasicInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByExampleSelective(@Param("record") TProjectBasicInfo record, @Param("example") TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") TProjectBasicInfo record, @Param("example") TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByExample(@Param("record") TProjectBasicInfo record, @Param("example") TProjectBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByPrimaryKeySelective(TProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(TProjectBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_project_basic_info
     *
     * @mbggenerated Tue Sep 18 16:26:10 CST 2018
     */
    int updateByPrimaryKey(TProjectBasicInfo record);
}