package com.epc.user.service.mapper.expert;

import com.epc.user.service.domain.expert.TExpertBasicInfo;
import com.epc.user.service.domain.expert.TExpertBasicInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TExpertBasicInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int countByExample(TExpertBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int deleteByExample(TExpertBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int insert(TExpertBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int insertSelective(TExpertBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    List<TExpertBasicInfo> selectByExampleWithRowbounds(TExpertBasicInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    List<TExpertBasicInfo> selectByExample(TExpertBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    TExpertBasicInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int updateByExampleSelective(@Param("record") TExpertBasicInfo record, @Param("example") TExpertBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int updateByExample(@Param("record") TExpertBasicInfo record, @Param("example") TExpertBasicInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int updateByPrimaryKeySelective(TExpertBasicInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    int updateByPrimaryKey(TExpertBasicInfo record);
}