package com.epc.platform.service.mapper.admin;

import com.epc.platform.service.domain.admin.SysAdminUserRole;
import com.epc.platform.service.domain.admin.SysAdminUserRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAdminUserRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int countByExample(SysAdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int deleteByExample(SysAdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int insert(SysAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int insertSelective(SysAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    List<SysAdminUserRole> selectByExampleWithRowbounds(SysAdminUserRoleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    List<SysAdminUserRole> selectByExample(SysAdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    SysAdminUserRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAdminUserRole record, @Param("example") SysAdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int updateByExample(@Param("record") SysAdminUserRole record, @Param("example") SysAdminUserRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int updateByPrimaryKeySelective(SysAdminUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_user_role
     *
     * @mbggenerated Mon Sep 10 16:52:59 CST 2018
     */
    int updateByPrimaryKey(SysAdminUserRole record);
}