package com.epc.platform.service.mapper.admin;

import com.epc.platform.service.domain.admin.RoleWithSource;
import com.epc.platform.service.domain.admin.SysAdminRole;
import com.epc.platform.service.domain.admin.SysAdminRoleCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAdminRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int countByExample(SysAdminRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int deleteByExample(SysAdminRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int insert(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int insertSelective(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    List<SysAdminRole> selectByExampleWithRowbounds(SysAdminRoleCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    List<SysAdminRole> selectByExample(SysAdminRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    SysAdminRole selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAdminRole record, @Param("example") SysAdminRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int updateByExample(@Param("record") SysAdminRole record, @Param("example") SysAdminRoleCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int updateByPrimaryKeySelective(SysAdminRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role
     *
     * @mbggenerated Mon Sep 10 16:50:56 CST 2018
     */
    int updateByPrimaryKey(SysAdminRole record);


    List<RoleWithSource> findById(Long roleId);

    List<SysAdminRole> findUserRole(String userName);
}