package com.epc.platform.service.mapper.admin;

import com.epc.platform.service.domain.admin.SysAdminRoleResource;
import com.epc.platform.service.domain.admin.SysAdminRoleResourceCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface SysAdminRoleResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int countByExample(SysAdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int deleteByExample(SysAdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int insert(SysAdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int insertSelective(SysAdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    List<SysAdminRoleResource> selectByExampleWithRowbounds(SysAdminRoleResourceCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    List<SysAdminRoleResource> selectByExample(SysAdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    SysAdminRoleResource selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int updateByExampleSelective(@Param("record") SysAdminRoleResource record, @Param("example") SysAdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int updateByExample(@Param("record") SysAdminRoleResource record, @Param("example") SysAdminRoleResourceCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int updateByPrimaryKeySelective(SysAdminRoleResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sys_admin_role_resource
     *
     * @mbggenerated Mon Sep 10 16:51:28 CST 2018
     */
    int updateByPrimaryKey(SysAdminRoleResource record);
}