package com.epc.web.service.mapper.operator;

import com.epc.web.service.domain.operator.TOperatorSupplier;
import com.epc.web.service.domain.operator.TOperatorSupplierCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TOperatorSupplierMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int countByExample(TOperatorSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int deleteByExample(TOperatorSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int insert(TOperatorSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int insertSelective(TOperatorSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    List<TOperatorSupplier> selectByExampleWithRowbounds(TOperatorSupplierCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    List<TOperatorSupplier> selectByExample(TOperatorSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    TOperatorSupplier selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int updateByExampleSelective(@Param("record") TOperatorSupplier record, @Param("example") TOperatorSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int updateByExample(@Param("record") TOperatorSupplier record, @Param("example") TOperatorSupplierCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int updateByPrimaryKeySelective(TOperatorSupplier record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_supplier
     *
     * @mbggenerated Wed Sep 26 10:35:18 CST 2018
     */
    int updateByPrimaryKey(TOperatorSupplier record);
}