package com.epc.web.service.mapper.operator;

import com.epc.web.service.domain.operator.TOperatorDetailInfo;
import com.epc.web.service.domain.operator.TOperatorDetailInfoCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TOperatorDetailInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int countByExample(TOperatorDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int deleteByExample(TOperatorDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int insert(TOperatorDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int insertSelective(TOperatorDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    List<TOperatorDetailInfo> selectByExampleWithRowbounds(TOperatorDetailInfoCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    List<TOperatorDetailInfo> selectByExample(TOperatorDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    TOperatorDetailInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int updateByExampleSelective(@Param("record") TOperatorDetailInfo record, @Param("example") TOperatorDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int updateByExample(@Param("record") TOperatorDetailInfo record, @Param("example") TOperatorDetailInfoCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int updateByPrimaryKeySelective(TOperatorDetailInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_operator_detail_info
     *
     * @mbggenerated Sun Sep 30 14:41:43 CST 2018
     */
    int updateByPrimaryKey(TOperatorDetailInfo record);

    TOperatorDetailInfo selectOperatorDetailByOperatorId(Long operatorId);

}