package com.epc.web.service.mapper.supplier;

import com.epc.web.service.domain.supplier.BSignUp;
import com.epc.web.service.domain.supplier.BSignUpCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface BSignUpMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int countByExample(BSignUpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int deleteByExample(BSignUpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int insert(BSignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int insertSelective(BSignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    List<BSignUp> selectByExampleWithRowbounds(BSignUpCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    List<BSignUp> selectByExample(BSignUpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    BSignUp selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int updateByExampleSelective(@Param("record") BSignUp record, @Param("example") BSignUpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int updateByExample(@Param("record") BSignUp record, @Param("example") BSignUpCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int updateByPrimaryKeySelective(BSignUp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_sign_up
     *
     * @mbggenerated Mon Oct 15 16:13:52 CST 2018
     */
    int updateByPrimaryKey(BSignUp record);


    List<BSignUp>  querySupplierProject(Long id);

}