package com.epc.web.service.mapper.supplier;

import com.epc.web.service.domain.supplier.TSupplierSign;
import com.epc.web.service.domain.supplier.TSupplierSignCriteria;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface TSupplierSignMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int countByExample(TSupplierSignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int deleteByExample(TSupplierSignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int insert(TSupplierSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int insertSelective(TSupplierSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    List<TSupplierSign> selectByExampleWithRowbounds(TSupplierSignCriteria example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    List<TSupplierSign> selectByExample(TSupplierSignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    TSupplierSign selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int updateByExampleSelective(@Param("record") TSupplierSign record, @Param("example") TSupplierSignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int updateByExample(@Param("record") TSupplierSign record, @Param("example") TSupplierSignCriteria example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int updateByPrimaryKeySelective(TSupplierSign record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_supplier_sign
     *
     * @mbggenerated Fri Sep 28 18:33:04 CST 2018
     */
    int updateByPrimaryKey(TSupplierSign record);
}