package com.epc.user.service.domain.expert;

import java.io.Serializable;
import java.util.Date;

public class TExpertBasicInfo implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.id
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.name
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.cellphone
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String cellphone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.profession
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String profession;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.positional
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String positional;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.level
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String level;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.circular_dt
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Date circularDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.circular_method
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String circularMethod;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.other_information
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String otherInformation;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.password
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.InviterType
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Integer invitertype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.InviterId
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Long inviterid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.state
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Integer state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.create_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Date createAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.update_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Date updateAt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_expert_basic_info.is_deleted
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private Integer isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.id
     *
     * @return the value of t_expert_basic_info.id
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.id
     *
     * @param id the value for t_expert_basic_info.id
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.name
     *
     * @return the value of t_expert_basic_info.name
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.name
     *
     * @param name the value for t_expert_basic_info.name
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.cellphone
     *
     * @return the value of t_expert_basic_info.cellphone
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getCellphone() {
        return cellphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.cellphone
     *
     * @param cellphone the value for t_expert_basic_info.cellphone
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setCellphone(String cellphone) {
        this.cellphone = cellphone == null ? null : cellphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.profession
     *
     * @return the value of t_expert_basic_info.profession
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getProfession() {
        return profession;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.profession
     *
     * @param profession the value for t_expert_basic_info.profession
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setProfession(String profession) {
        this.profession = profession == null ? null : profession.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.positional
     *
     * @return the value of t_expert_basic_info.positional
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getPositional() {
        return positional;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.positional
     *
     * @param positional the value for t_expert_basic_info.positional
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setPositional(String positional) {
        this.positional = positional == null ? null : positional.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.level
     *
     * @return the value of t_expert_basic_info.level
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getLevel() {
        return level;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.level
     *
     * @param level the value for t_expert_basic_info.level
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setLevel(String level) {
        this.level = level == null ? null : level.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.circular_dt
     *
     * @return the value of t_expert_basic_info.circular_dt
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Date getCircularDt() {
        return circularDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.circular_dt
     *
     * @param circularDt the value for t_expert_basic_info.circular_dt
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setCircularDt(Date circularDt) {
        this.circularDt = circularDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.circular_method
     *
     * @return the value of t_expert_basic_info.circular_method
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getCircularMethod() {
        return circularMethod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.circular_method
     *
     * @param circularMethod the value for t_expert_basic_info.circular_method
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setCircularMethod(String circularMethod) {
        this.circularMethod = circularMethod == null ? null : circularMethod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.other_information
     *
     * @return the value of t_expert_basic_info.other_information
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getOtherInformation() {
        return otherInformation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.other_information
     *
     * @param otherInformation the value for t_expert_basic_info.other_information
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setOtherInformation(String otherInformation) {
        this.otherInformation = otherInformation == null ? null : otherInformation.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.password
     *
     * @return the value of t_expert_basic_info.password
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.password
     *
     * @param password the value for t_expert_basic_info.password
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.InviterType
     *
     * @return the value of t_expert_basic_info.InviterType
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Integer getInvitertype() {
        return invitertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.InviterType
     *
     * @param invitertype the value for t_expert_basic_info.InviterType
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setInvitertype(Integer invitertype) {
        this.invitertype = invitertype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.InviterId
     *
     * @return the value of t_expert_basic_info.InviterId
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Long getInviterid() {
        return inviterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.InviterId
     *
     * @param inviterid the value for t_expert_basic_info.InviterId
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setInviterid(Long inviterid) {
        this.inviterid = inviterid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.state
     *
     * @return the value of t_expert_basic_info.state
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.state
     *
     * @param state the value for t_expert_basic_info.state
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.create_at
     *
     * @return the value of t_expert_basic_info.create_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Date getCreateAt() {
        return createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.create_at
     *
     * @param createAt the value for t_expert_basic_info.create_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setCreateAt(Date createAt) {
        this.createAt = createAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.update_at
     *
     * @return the value of t_expert_basic_info.update_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Date getUpdateAt() {
        return updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.update_at
     *
     * @param updateAt the value for t_expert_basic_info.update_at
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setUpdateAt(Date updateAt) {
        this.updateAt = updateAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_expert_basic_info.is_deleted
     *
     * @return the value of t_expert_basic_info.is_deleted
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public Integer getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_expert_basic_info.is_deleted
     *
     * @param isDeleted the value for t_expert_basic_info.is_deleted
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    public void setIsDeleted(Integer isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_expert_basic_info
     *
     * @mbggenerated Thu Sep 13 19:52:50 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", cellphone=").append(cellphone);
        sb.append(", profession=").append(profession);
        sb.append(", positional=").append(positional);
        sb.append(", level=").append(level);
        sb.append(", circularDt=").append(circularDt);
        sb.append(", circularMethod=").append(circularMethod);
        sb.append(", otherInformation=").append(otherInformation);
        sb.append(", password=").append(password);
        sb.append(", invitertype=").append(invitertype);
        sb.append(", inviterid=").append(inviterid);
        sb.append(", state=").append(state);
        sb.append(", createAt=").append(createAt);
        sb.append(", updateAt=").append(updateAt);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}